apiVersion: v1
kind: Service
metadata:
  labels:
    app: alpine
  name: alpine
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    app: alpine
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpine
  name: alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  strategy: {}
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
        - image: indefinitefuture/alpine:amd64
          name: alpine
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: alpine
  name: alpine
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - hosts:
        - alpine.f0232020.hkbu.app
      secretName: alpine-certs
  rules:
  - host: "alpine.f0232020.hkbu.app"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: alpine
            port:
              number: 8080